# docker-compose.yml
version: '3.8'

services:
  db-local:
    image: postgres:15-alpine
    container_name: db-local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carrosdb
    ports:
      - "5425:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: